#pragma config(Sensor, in1,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    levelPot,       sensorPotentiometer)
#pragma config(Motor,  port2,           rf,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lf,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armLift,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           clawClamp,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           clawLevel,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rb,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lb,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armLift2,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*																					Notes
motor speed ranges -127 to 127
joystick input ranges from -127 to 127
potentiometer input ranges 5 to 4095
distance sensor is in centimeters
*/
task main()
{
	float level=0;
	const short accuracy = 150;
	while(true)
	{
		//level = 1.0556*SensorValue[liftPot]-11.20558;
		//level = SensorValue[liftPot]-11.20558;
		level = .75*SensorValue[liftPot]+12.8;
		//motor[rf] = (vexRT[Ch3]-vexRT[Ch4])/2;
		//motor[lf] = (vexRT[Ch3]+vexRT[Ch4])/2;
		motor[rf] = vexRT[Ch2];
		motor[rb] = vexRT[Ch2];
		motor[lf] = vexRT[Ch3];
		motor[lb] = vexRT[Ch3];
		if(vexRT[Btn5U]==1 && SensorValue[liftPot] > 630)
		{
			motor[armLift] = 75;
			motor[armLift2] = 75;
		}
		else if(vexRT[Btn5D] ==1 && SensorValue[liftPot] < 2830)
		{
			motor[armLift] = -75;
			motor[armLift2] = -75;
		}
		else
		{
			motor[armLift2] = 7;
			motor[armLift] = 7;
		}
		//claw clamp control
		motor[clawClamp] = (vexRT[Btn6U]-vexRT[Btn6D])*(100/127);/*multiply by the amount of power*/
		if(SensorValue[levelPot] <  level - accuracy)
		{
			motor[clawLevel] = 50;
		}
		else if(SensorValue[levelPot] >  level + accuracy)
		{
			motor[clawLevel] = -50;
		}
		else
		{
			motor[clawLevel] = 0;
		}
	}
}
